version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: session-bot
    volumes:
      - ./sessions:/app/sessions
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URI_SESSIONS_F=${DATABASE_URI_SESSIONS_F}
      - LOG_CHANNEL_SESSIONS_FILES=${LOG_CHANNEL_SESSIONS_FILES}
    restart: unless-stopped
