services:
  - type: web
    name: telegram-session-bot
    env: python
    startCommand: python3 bot.py
    buildCommand: pip install -r requirements.txt
    repo: https://github.com/TonyStark-Botz/telegram-session-bot
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    autoDeploy: true
